name: 'Deploy'

on: 
  workflow_dispatch:


env:
  TF_LOG: INFO

defaults:
  shell: bash

jobs:
  terraform:
    name: 'Terraform based deployment'
    environment: Development
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    runs-on: ubuntu-latest

    steps:
    # The order of checkouts is important because of cleaning and the step afterwards will not find anything
    # unless there is a specific path specified!

    # Checkout client files to root folder
    - name: Checkout Client
      uses: actions/checkout@v3


    # Checkout the module repository to separate folder protecting root file system    
    - name: Checkout Modules
      uses: actions/checkout@v3
      with:
        repository: WolfgangBaeck/REB3Modules
        path: modules

    - name: Show FileSystem
      run: ls -R

    - name: Run Terraform Action
      uses: ./modules/.github/actions/terraformdeploy
